<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="3" time="75.17">
 <testsuite name="&apos;Login to the application&apos; form" timestamp="2019-01-22T13:00:47" hostname="localhost" time="75.17" errors="0" tests="3" skipped="0" disabled="0" failures="1">
  <testcase classname="&apos;Login to the application&apos; form" name="Submit without username and password inputs" time="8.496" />
  <testcase classname="&apos;Login to the application&apos; form" name="Submit with only valid username" time="3.525" />
  <testcase classname="&apos;Login to the application&apos; form" name="Submit valid username and valid password" time="63.142">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\onimalarathna\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>